### PR TITLE
Change Order For Potentially Better Flow

### PR DESCRIPTION
**Pull request by manavm1990**
Based on some of our in-person discussions yesterday, I have, first of all moved specificity information to be closer to the sections on positioning, etc.

Furthermore, as a whole, I moved Style content into it's own section. Prior to this move, the part about creating an external style sheet came significantly later in the course materials - even after specificity, and based on experience in course and our chats, that doesn't seem to be the ideal flow.

### CODE REVIEW

**Comment by manavm1990** [comment]
IG this is 🆗 to 'clean up' some markup to use the 'new' HTML5 tags we discussed: `<header>` and `<nav>`.

**Comment by manavm1990** [comment]
Let's use `const` and `let`! We still mention `var`.

**Comment by manavm1990** [comment]
I didn't see the most recent updates regarding `const`, `let`, etc. Am I doing something wrong with the _pull request?_

**Comment by NAlexPear** [comment]
Closing this as a duplicate of #12 (let me know if that's correct, though)

**Pull request closed without merging**
